name: Compilar APK

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Hacer gradlew ejecutable
        run: chmod +x ./gradlew

      - name: Compilar APK Debug
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: DirectDance-APK
          path: app/build/outputs/apk/debug/app-debug.apk
